<?php

namespace AppBundle\Repository;

/**
 * operation_tRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class operation_tRepository extends \Doctrine\ORM\EntityRepository
{
}
